CACHE_MODE: False
DATASET:
  COCO_PANOPTIC_PATH: None
  COCO_PATH: ../datasets
  DATASET_FILE: cityscapes_to_foggy_cityscapes
  DA_MODE: uda
  NUM_CLASSES: 4
  REMOVE_DIFFICULT: False
DEVICE: cuda
DIST:
  DISTRIBUTED: True
  DIST_BACKEND: nccl
  DIST_URL: env://
  GPU: 0
  RANK: 0
  WORLD_SIZE: 4
EVAL: False
LOSS:
  AUX_LOSS: True
  BACKBONE_LOSS_COEF: 0.1
  BBOX_LOSS_COEF: 5.0
  CHANNEL_QUERY_LOSS_COEF: 0.1
  CLS_LOSS_COEF: 2.0
  DA_GAMMA: 0
  DICE_LOSS_COEF: 1.0
  FOCAL_ALPHA: 0.25
  GIOU_LOSS_COEF: 2.0
  INSTANCE_QUERY_LOSS_COEF: 0.1
  MASK_LOSS_COEF: 1.0
  SET_COST_BBOX: 5.0
  SET_COST_CLASS: 2.0
  SET_COST_GIOU: 2.0
  SPACE_QUERY_LOSS_COEF: 0.1
  CATEGORY_QUERY_LOSS_COEF: 0.1
  PROTOTYPE_ALIGN_LOSS_COEF: 0.1
MODEL:
  BACKBONE: resnet50
  PROTOTYPE_ALIGN: True
  BACKBONE_ALIGN: False
  CHANNEL_ALIGN: True
  DEC_LAYERS: 6
  DEC_N_POINTS: 4
  DILATION: False
  DIM_FEEDFORWARD: 1024
  DROPOUT: 0.1
  ENC_LAYERS: 6
  ENC_N_POINTS: 4
  FROZEN_WEIGHTS: None
  HIDDEN_DIM: 256
  INSTANCE_ALIGN: True
  MASKS: False
  NHEADS: 8
  NUM_FEATURE_LEVELS: 1
  NUM_QUERIES: 300
  POSITION_EMBEDDING: sine
  POSITION_EMBEDDING_SCALE: 6.283185307179586
  SPACE_ALIGN: True
  TWO_STAGE: False
  WITH_BOX_REFINE: True
  MEMORY_DIM: 256
  MEMORY_SIZE: 180
  CATEGORY_ALIGN: False
  STAGE: retrain

NUM_WORKERS: 2
OUTPUT_DIR: exps/embedding_vis
RESUME:
SEED: 42
START_EPOCH: 0
TRAIN:
  BATCH_SIZE: 2
  CLIP_MAX_NORM: 0.1
  EPOCHS: 200
  LR: 0.0002
  LR_BACKBONE: 2e-05
  LR_BACKBONE_NAMES: ['backbone.0']
  LR_DROP: 40
  LR_DROP_EPOCHS: None
  LR_LINEAR_PROJ_MULT: 0.1
  LR_LINEAR_PROJ_NAMES: ['reference_points', 'sampling_offsets']

  # TODO: choose to not pass the domain attention modules
  DOMAIN_ATTENTION_NAMES: ['space_attn', 'instance_attn', 'channel_attn']
  DOMAIN_DISCRIMINATOR_NAMES: ['space_D', 'channel_D', 'instance_D']

  LR_ENCODER: 1e-05
  ENCODER_NAMES: ['encoder'] # set for a different learning rate

  LR_DECODER: 1e-05
  DECODER_NAMES: ['decoder']

  LR_MULTI_LABEL_CLASSIFIER: 1e-05
  MULTI_LABEL_CLASSIFIER_NAMES: ['multi_label_classifier']

  SGD: False
  WEIGHT_DECAY: 0.0001